name: Deploy Flashloan Smart Contract

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc
          foundryup

      - name: Install Dependencies
        run: |
          forge install

      - name: Compile Smart Contract
        run: forge build

      - name: Deploy to Polygon Testnet (Amoy)
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          POLYGON_RPC_URL: "https://rpc-amoy.polygon.technology"
        run: |
          forge create --rpc-url $POLYGON_RPC_URL --private-key $PRIVATE_KEY contracts/FlashLoanArbitrage.sol:FlashLoanArbitrage
